# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: node:latest

services:
- name: postgres:latest
  alias: localhost

variables:
  POSTGRES_DB: prisma
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
- install
- lint
- test
- migrate
- build
- deploy

install:
  stage: install
  script:
  - npm install

lint:
  stage: lint
  script:
  - npm install
  - npm run lint

sast:
  stage: test

migrate:
  stage: migrate
  script:
  - npm install
  - npx prisma generate
  - npx prisma migrate deploy

build:
  stage: build
  script:
  - npm install
  - npm run build

deploy:
  stage: deploy
  script:
  - curl -s http://xiny.ca:8080/

include:
- template: Security/SAST.gitlab-ci.yml
